// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7FG5jDjrp3k7TXRHVvN1HzO36SJusR4E',
    appId: '1:274861978364:web:b1116a2d5d2d9007135d79',
    messagingSenderId: '274861978364',
    projectId: 'ecommercefirebase-86523',
    authDomain: 'ecommercefirebase-86523.firebaseapp.com',
    storageBucket: 'ecommercefirebase-86523.appspot.com',
    measurementId: 'G-SH2LCZMFZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7XJpEmCUF-OK4G6KDpF3mkNVRmD5VWLU',
    appId: '1:274861978364:android:552f7943b3e2227f135d79',
    messagingSenderId: '274861978364',
    projectId: 'ecommercefirebase-86523',
    storageBucket: 'ecommercefirebase-86523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVbSqH5b1w9TLYvedSGb4T4e48pLpiGh4',
    appId: '1:274861978364:ios:079477716a59feed135d79',
    messagingSenderId: '274861978364',
    projectId: 'ecommercefirebase-86523',
    storageBucket: 'ecommercefirebase-86523.appspot.com',
    iosBundleId: 'com.example.ecommerceAdminFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVbSqH5b1w9TLYvedSGb4T4e48pLpiGh4',
    appId: '1:274861978364:ios:96cdda370c17c457135d79',
    messagingSenderId: '274861978364',
    projectId: 'ecommercefirebase-86523',
    storageBucket: 'ecommercefirebase-86523.appspot.com',
    iosBundleId: 'com.example.ecommerceAdminFirebase.RunnerTests',
  );
}
